### ISSUE TITLE
Talkback Beta v3.8.0-r46 and r47 reproducably crashes after start with German locales

### ISSUE THREAD

**Issue by GoogleCodeExporter** [clc/eyes-free#103]
```
What steps will reproduce the problem?
1. Set your device language to German
2. Install Talkback v3.0.8-r47
3. Enable Talkback and note that it will crash immediately

After switching the device language to English (UK), Talkback works as expected.

I'm using a Sony Ericson Xperia Pro with Android 4.0.4 (inofficial rom)

The following is the logcat out I get after enabling Talkback:

---snip---
I/ActivityManager(  219): Start proc com.google.android.marvin.talkback for 
service com.google.android.marvin.talkback/.TalkBackService: pid=3421 uid=10058 
gids={3002}
W/InputManagerService(  219): Window already focused, ignoring focus gain of: 
com.android.internal.view.IInputMethodClient$Stub$Proxy@2bb171b0
I/ActivityThread( 3421): Pub 
com.google.android.marvin.talkback.providers.StatusProvider: 
com.google.android.marvin.talkback.StatusProvider
E/SpeechController( 3421): Starting TTS engine: com.google.android.tts
I/TextToSpeech( 3421): Sucessfully bound to com.google.android.tts
I/SVOX Pico Engine( 3307): loaded de-DE successfully
I/TextToSpeech( 3421): Connected to 
ComponentInfo{com.google.android.tts/com.google.android.tts.GoogleTTSService}
D/AndroidRuntime( 3421): Shutting down VM
W/dalvikvm( 3421): threadid=1: thread exiting with uncaught exception 
(group=0x2b4e51f8)
E/AndroidRuntime( 3421): FATAL EXCEPTION: main
E/AndroidRuntime( 3421): java.util.MissingFormatArgumentException: Format 
specifier:  d
E/AndroidRuntime( 3421):    at 
java.util.Formatter.getArgument(Formatter.java:1109)
E/AndroidRuntime( 3421):    at java.util.Formatter.doFormat(Formatter.java:1074)
E/AndroidRuntime( 3421):    at java.util.Formatter.format(Formatter.java:1040)
E/AndroidRuntime( 3421):    at java.util.Formatter.format(Formatter.java:1009)
E/AndroidRuntime( 3421):    at java.lang.String.format(String.java:1998)
E/AndroidRuntime( 3421):    at 
android.content.res.Resources.getString(Resources.java:361)
E/AndroidRuntime( 3421):    at android.content.Context.getString(Context.java:295)
E/AndroidRuntime( 3421):    at 
com.google.android.marvin.talkback.RingerModeAndScreenMonitor.appendRingerStateA
nouncement(RingerModeAndScreenMonitor.java:316)
E/AndroidRuntime( 3421):    at 
com.google.android.marvin.talkback.RingerModeAndScreenMonitor.handleRingerModeCh
anged(RingerModeAndScreenMonitor.java:238)
E/AndroidRuntime( 3421):    at 
com.google.android.marvin.talkback.RingerModeAndScreenMonitor.internalOnReceive(
RingerModeAndScreenMonitor.java:126)
E/AndroidRuntime( 3421):    at 
com.google.android.marvin.talkback.RingerModeAndScreenMonitor.access$0(RingerMod
eAndScreenMonitor.java:112)
E/AndroidRuntime( 3421):    at 
com.google.android.marvin.talkback.RingerModeAndScreenMonitor$1.handleOnReceive(
RingerModeAndScreenMonitor.java:65)
E/AndroidRuntime( 3421):    at 
com.google.android.marvin.talkback.BroadcastHandler.handleMessage(BroadcastHandl
er.java:33)
E/AndroidRuntime( 3421):    at android.os.Handler.dispatchMessage(Handler.java:99)
E/AndroidRuntime( 3421):    at android.os.Looper.loop(Looper.java:137)
E/AndroidRuntime( 3421):    at 
android.app.ActivityThread.main(ActivityThread.java:4575)
E/AndroidRuntime( 3421):    at java.lang.reflect.Method.invokeNative(Native 
Method)
E/AndroidRuntime( 3421):    at java.lang.reflect.Method.invoke(Method.java:511)
E/AndroidRuntime( 3421):    at 
com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:789)
E/AndroidRuntime( 3421):    at 
com.android.internal.os.ZygoteInit.main(ZygoteInit.java:556)
E/AndroidRuntime( 3421):    at dalvik.system.NativeStart.main(Native Method)
I/Process ( 3421): Sending signal. PID: 3421 SIG: 9
I/ActivityManager(  219): Process com.google.android.marvin.talkback (pid 3421) 
has died.
---snip---

```

Original issue reported on code.google.com by `Henning....@googlemail.com` on 7 Jun 2012 at 1:59

**Comment by GoogleCodeExporter** [comment]
Original comment by `caseybur...@google.com` on 14 Aug 2012 at 12:06
- Changed state: **Fixed**
