### ISSUE TITLE
[Eyes-Free Keyboard] NullPointerException in LatinIME.updateSuggestions()

### ISSUE THREAD

**Issue by GoogleCodeExporter** [clc/eyes-free#79]
```
What steps will reproduce the problem?
1.Reset factory data
2.When DUT restart at welcome screen make a MT call(AS attached picture shows) 


What is the expected output? What do you see instead?

[Actual Result]
DUT force close (com.google.android.marvin.feedback)

[Expected Result ]
normal 

What version of the product are you using? On what operating system?
apk:talkback v23 (2.7.7) ,Android Version 2.3.7

Please provide any additional information below.

java.lang.NullPointerException
at 
com.googlecode.eyesfree.inputmethod.latin.LatinIME.updateSuggestions(LatinIME.ja
va:1989)
at 
com.googlecode.eyesfree.inputmethod.latin.LatinIME.requestKeyboardMode(LatinIME.
java:1282)
at 
com.googlecode.eyesfree.inputmethod.latin.LatinIME.access$100(LatinIME.java:92)
at 
com.googlecode.eyesfree.inputmethod.latin.LatinIME$1.onCallStateChanged(LatinIME
.java:224)
at 
android.telephony.PhoneStateListener$2.handleMessage(PhoneStateListener.java:336
)
at android.os.Handler.dispatchMessage(Handler.java:99)
at android.os.Looper.loop(Looper.java:130)
at android.app.ActivityThread.main(ActivityThread.java:3683)
at java.lang.reflect.Method.invokeNative(Native Method)
at java.lang.reflect.Method.invoke(Method.java:507)
at 
com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:895)
at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:653)
at dalvik.system.NativeStart.main(Native Method)
```

Original issue reported on code.google.com by `jfoxc...@gmail.com` on 4 Jan 2012 at 6:24

**Comment by GoogleCodeExporter** [comment]
```
The DUT shows "The application TalkBack(process 
com.google.android.marvin.feedback) has stopped unexpectedly. please try again."

I have built another new apk of talkback by the source Code. but it fail.
I am waittting someone who can help me
```

Original comment by `jfoxc...@gmail.com` on 4 Jan 2012 at 6:41

**Comment by GoogleCodeExporter** [comment]
Original comment by `alanv@google.com` on 27 May 2012 at 5:20
- Changed title: **[Eyes-Free Keyboard] NullPointerException in LatinIME.updateSuggestions()**
- Added labels: **Type-Defect**, **Priority-Medium**

**Comment by GoogleCodeExporter** [comment]
```
Issue 81 has been merged into this issue.
```

Original comment by `alanv@google.com` on 27 May 2012 at 5:21

**Comment by GoogleCodeExporter** [comment]
Original comment by `alanv@google.com` on 29 May 2013 at 7:53
